### ISSUE TITLE
problem with import probe.probe11

### ISSUE THREAD

**Issue by gydini835** [KVSlab/OasisMove#30]
I try to pass test in VamPy and that return pre_boundary_condition is not defined
![Screenshot from 2024-01-14 17-35-35](https://github.com/KVSlab/OasisMove/assets/47323234/88dcfdd6-4691-48a8-8311-78bc89b31751)

HELP PLS @hkjeldsberg

**Comment by hkjeldsberg** [comment]
Hi @gydini835,

Thanks for reporting this issue. Could you provide the command you used to run `oasismove`, and which operating system you are running on?

Best,
Henrik
