### ISSUE TITLE
ask help for the ventricle project

### ISSUE THREAD

**Issue by whucsu** [KVSlab/OasisMove#31]
there is another project link : https://github.com/KVSlab/OasisMoveFork for years.
here the Cover image is the left Left atrium with data set link，so can anyone share the ventricle model and the examples that could run ?
thanks.

**Comment by hkjeldsberg** [comment]
Dear @whucsu,

The ventricle model you saw on https://github.com/KVSlab/OasisMoveFork (now deleted) was shared with me by Dr. Vijay Vedula (https://www.me.columbia.edu/faculty/vijay-vedula) and should still be available upon request. You can contact him directly for access.

Best regards,
Henrik
